FROM node:20-alpine AS build

WORKDIR /app/client

COPY client/package.json client/tsconfig.json client/tsconfig.node.json client/vite.config.ts ./
RUN npm install

COPY client/src ./src
COPY client/index.html ./
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
